[nix]
channel = "nixpkgs-unstable"  # Forces Railway to use the latest packages

[phases.setup]
nixPkgs = ["nodejs-20_x", "ffmpeg"]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node index.js"

[deploy]
port = 3000
